Fix missing gdbstub dependency in Makefile
When compiling with ENABLE_GDBSTUB=1 using the command:

make ENABLE_GDBSTUB=1 -j$(nproc)

The following compilation error occurs:

In file included from src/syscall.c:14:
src/riscv_private.h:11:10: fatal error: mini-gdbstub/include/gdbstub.h: No such file or directory
   11 | #include "mini-gdbstub/include/gdbstub.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:213: build/syscall.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/softfloat.h:11,
                 from src/emulate.c:19:
src/riscv_private.h:11:10: fatal error: mini-gdbstub/include/gdbstub.h: No such file or directory
   11 | #include "mini-gdbstub/include/gdbstub.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:212: build/emulate.o] Error 1
In file included from src/riscv.c:28:
src/riscv_private.h:11:10: fatal error: mini-gdbstub/include/gdbstub.h: No such file or directory
   11 | #include "mini-gdbstub/include/gdbstub.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

The error is due to the improper handling of the gdbstub library
dependency in the Makefile. This patch ensures that the gdbstub library
is correctly compiled before source files that depend on it.