Fix compiler errors with JIT when Zbs is disabled
When using 'make ENABLE_Zbs=0 ENABLE_JIT=1', the following errors are
observed:

src/jit.c:1760:17: error: ‘do_bseti’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_bset’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_binvi’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_binv’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_bexti’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_bext’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_bclri’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_bclr’ defined but not used [-Werror=unused-function
]
Include "Zbs" in EXT_LIST to ensure instructions like `bseti`, `bset`,
and `bclr`  are properly handled, resolving unused function errors
during JIT builds.