Fix Clang error when disabling Zicsr
When using 'make ENABLE_Zicsr=0 CC=clang', the following error is
observed:

src/emulate.c:83:20: error: unused function 'update_time' [-Werror,-Wunused-function]
   83 | static inline void update_time(riscv_t *rv)
      |                    ^~~~~~~~~~~
1 error generated

Fix this by guarding the update_time function definition with
RV32_HAS(Zicsr) macro. This ensures the function is only defined
when the Zicsr is enabled.