Fix Clang error with JIT when EXT_M is disabled
When using 'make ENABLE_EXT_M=0 ENABLE_JIT=1 CC=clang', the following
error is observed:

src/jit.c:728:20: error: unused function 'emit_alu64_imm8' [-Werror,-Wunused-function]
  728 | static inline void emit_alu64_imm8(struct jit_state *state,
      |                    ^~~~~~~~~~~~~~~

Fix this by guarding the 'emit_alu64_imm8' function definition with
RV32_HAS(EXT_M) macro. This ensures the function is only defined
when the EXT_M is enabled.